AllCops:
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"

Rails:
  Enabled: true

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

inherit_from: .rubocop_todo.yml
