services:

- type: web
  name: eatmore
  env: ruby
  numInstances: 1
  buildCommand: bin/build
  startCommand: bin/start
  autoDeploy: true
  domains:
  - eatmore.io
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: eatmore
      property: connectionString

databases:
- name: eatmore
