services:

- type: web
  name: eatmore
  env: ruby
  numInstances: 1
  buildCommand: bin/build
  startCommand: bin/start
  autoDeploy: true
  domains:
  - eatmore.io
  envVars:
  - fromGroup: expensivechat
  - key: DATABASE_URL
    fromDatabase:
      name: eatmore
      property: connectionString

- type: cron
  name: eatmore-cron
  env: ruby
  schedule: "0 * * * *"
  buildCommand: bin/build
  startCommand: rake reminders:send
  envVars:
  - fromGroup: expensivechat
  - key: DATABASE_URL
    fromDatabase:
      name: eatmore
      property: connectionString

envVarGroups:
- name: eatmore
  envVars:
  - key: BUGSNAG_API_KEY
    sync: false

databases:
- name: eatmore
