services:

- type: web
  name: eatmore
  env: ruby
  numInstances: 1
  buildCommand: bin/build
  startCommand: bin/start
  autoDeploy: true
  domains:
  - eatmore.io
  envVars:
  - fromGroup: eatmore
  - key: DATABASE_URL
    fromDatabase:
      name: eatmore
      property: connectionString

- type: cron
  name: eatmore-cron
  env: ruby
  schedule: "0 * * * *"
  buildCommand: bin/build
  startCommand: rake reminders:send
  envVars:
  - fromGroup: eatmore
  - key: DATABASE_URL
    fromDatabase:
      name: eatmore
      property: connectionString

envVarGroups:
- name: eatmore
  envVars:
  - key: HOST
    sync: false
  - key: S3_ACCESS_KEY_ID
    sync: false
  - key: S3_BUCKET
    sync: false
  - key: S3_REGION
    sync: false
  - key: S3_SECRET_ACCESS_KEY
    sync: false
  - key: SECRET_KEY_BASE
    sync: false
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: TELEGRAM_BOT_USERNAME
    sync: false
  - key: BUGSNAG_API_KEY
    sync: false

databases:
- name: eatmore
